### ISSUE TITLE
Connect a generated workspace to Goldstack source using `yarn link`

### ISSUE THREAD

**Issue by chrismilleruk** [goldstack/goldstack#121]
Related to https://github.com/goldstack/goldstack/issues/103 but using a different technique.

Running the following from the generated project:
`yarn link /path/to/goldstack/monorepo/root/ -Apr`

.. will populate the `package.json/resolutions` section and force the generated project to use goldstack monorepo modules from source.

At a minimum, this supports `yarn template-ts` invocations much like #103 but might also support a better `git` workflow in the generated project.

_Originally posted by @chrismilleruk in https://github.com/goldstack/goldstack/issues/103#issuecomment-1051104331_

**Comment by mxro** [comment]
Thanks, I tested this and actually find this is superior to the method originally suggested in #103 - so I updated the docs there!

**Comment by chrismilleruk** [comment]
Looks great!
