### ISSUE TITLE
utils-typescript-references - reference to one tsconfig filename but update another

### ISSUE THREAD

**Issue by dobesv** [goldstack/goldstack#132]
_Request_

It would be useful if the `utils-typescript-references` would update `tsconfig.json` with references to `tsconfig.build.json` (or whatever name) files in packages.

_Background_

In our project we have two tsconfig files per project, one which is used to build the package and one which is used for type checking.

The one that is used for type checking (`tsconfig.json`) doesn't output the files and includes test files (e.g. `*/**.test.ts`)

The one that is used for building (`tsconfig.build.json`) extends `tsconfig.json` but excludes test files and emits `.d.ts` files for use by other packages.

**Comment by mxro** [comment]
Yes I think it is quite common to have more than one TypeScript configuration file. Many packages in this project have that as well, see [app-nextjs-bootstrap](https://github.com/goldstack/goldstack/tree/master/workspaces/templates/packages/app-nextjs-bootstrap)

![image](https://user-images.githubusercontent.com/1448524/158033155-d16f2b16-609d-486d-a706-8421727cf975.png)

Here it is implemented by  `tsconfig.local.json` extending `tsconfig.json`:

```json
{
  "extends": "./tsconfig.json"
}
```

This only works though when they all inherit from the same base file. Would this approach work for you?

Alternatively, I think we could add an additional parameter such as `--configName tsconfig.build.json --configName tsconfig.compile.json` that will scan for these file names in every project folder, and if they exist, inject the references?

**Comment by dobesv** [comment]
Our `tsconfig.build.json` files do inherit from `tsconfig.json` and just change the build settings and exclude test files.

What I want is for the references to point to `tsconfig.build.json` but be inserted into `tsconfig.json`.  That way when I do a recursive build, it uses the build file(s) for building.

That said, I'm not super confident this is the right approach, though.  Maybe I need to dig into whether this is needed or if just having all the references between the `tsconfig.json` files would work just as well.  Or if the references should only be between `tsconfig.build.json` files.  

I think my IDE (WebStorm) automatically detects the `tsconfig.json` files and uses those for its own type checking purposes, and also the references are used for definition lookup.  So the `tsconfig.json` files probably benefit from having the references.  But if `tsconfig.build.json` extends `tsconfig.json` does it actually inherit the `references` from it?

**Comment by mxro** [comment]
It looks like `references` are [excluded](https://github.com/microsoft/TypeScript/issues/27098) [from inheritance](https://www.typescriptlang.org/tsconfig#extends):

> Currently, the only top-level property that is excluded from inheritance is [references](https://www.typescriptlang.org/tsconfig#references).

And if I understand the documentation [What is a Project Reference?](https://www.typescriptlang.org/docs/handbook/project-references.html#what-is-a-project-reference) correctly, the path could become a full path to a config file, thus instead of

https://github.com/goldstack/goldstack/blob/master/workspaces/templates-lib/packages/template-lambda-api/tsconfig.json#L13

```json
    {
      "path": "../infra"
    },
```

We could have something like:

```json
    {
      "path": "../infra/tsconfig.build.json"
    },
```

>

**Comment by dobesv** [comment]
Ah this is probably not a good idea, then.  I should have all the references in and between the tsconfig.json files by the looks of it.

**Comment by mxro** [comment]
Yeah, as I wrote references are excluded from inheritance, so there may be some utility in injecting the references into different or multiple tsconfig files. Let me know how you go!

**Comment by dobesv** [comment]
I'm working on this a bit to support a structure like this:

- `tsconfig.build.json` - excludes test files, emits `.d.ts` files (and maybe `.js` files), references other projects' `tsconfig.build.json` files
- `tsconfig.json` - includes test files, does not emit any files, and references `tsconfig.build.json`

When I run the tool I would pass `--tsConfigName tsconfig.build.json --tsConfigName tsconfig.json` and it would always update `tsconfig.build.json` in preference to `tsconfig.json` if available.  It would skip packages with neither of these.

If I passed just `--tsConfigName tsconfig.build.json` it would only look for `tsconfig.json` and not update or generate references to any `tsconfig.json` files.

Do you think this would work for your use case(s) and others' ?

**Comment by mxro** [comment]
I think the PR should cover all use cases I can think of at the moment nicely 👌

**Comment by mxro** [comment]
Assuming we can close this issue?
