### ISSUE TITLE
utils-typescript-references - do not write file if contents unchanged

### ISSUE THREAD

**Issue by dobesv** [goldstack/goldstack#133]
It's more friendly not to re-write a file with the same contents.  This leaves the file mtime untouched, avoids triggering file watchers, and so on.

Currently the tool unconditionally writes out the file.

**Comment by mxro** [comment]
Thanks for raising this issue. Yes, that is a great idea. Will add this to the backlog.

**Comment by mxro** [comment]
Released with [`@goldstack/utils-typescript-references@0.1.7`](https://www.npmjs.com/package/@goldstack/utils-typescript-references) - Please confirm this was what you are looking for and it works for you!
