### ISSUE TITLE
utils-typescript-references - ignore dependencies without tsconfig.json

### ISSUE THREAD

**Issue by dobesv** [goldstack/goldstack#134]
If a workspace doesn't have a `tsconfig.json` it should be skipped by this tool and not written into `references`.

**Comment by mxro** [comment]
Yes absolutely, this makes sense. The tool already skips processing packages without a `tsconfig.json` but may still include them in the references. Will add this to the backlog as well.

**Comment by mxro** [comment]
Released with [`@goldstack/utils-typescript-references@0.1.7`](https://www.npmjs.com/package/@goldstack/utils-typescript-references) - Please confirm this was what you are looking for and it works for you!

**Comment by dobesv** [comment]
That was fast!
