### ISSUE TITLE
Error: no matching Route53Zone found

### ISSUE THREAD

**Issue by trevorallred** [goldstack/goldstack#169]
Hi, I am trying to deploy a lambda based on the Serverless API template. I successfully deployed dev and defined my Route53Zone in the dev account. Everything worked fine. Now I tried to deploy into prod, which is in a different AWS account, but I'm getting the following error:

```
Error: no matching Route53Zone found
│
│   with data.aws_route53_zone.main,
│   on domain.tf line 3, in data "aws_route53_zone" "main":
│    3: data "aws_route53_zone" "main" {
```

This makes sense because my zone is defined in the dev aws account. Do you have any suggestions for how to resolve this?

Also, should Route53Zone be defined in my master aws account so it's not connected to my dev account?

**Comment by mxro** [comment]
Hello, thanks for raising this issue!

Yes, in order for Terraform to be able to run successfully the Hosted Zone Domain must point to a hosted zone that is in the same account as all the other resources we are trying to deploy.

So for instance:

|Hosted Zone Domain|AWS Account|
|-|-|
|dev.mydomain.com|Dev Account|
|mydomain.com|Prod Account|

I think a good pattern is to define the Route 53 zone for your main domain in your Prod account (such as `mydomain.com`). Then one can create another Route 53 zone in the Dev account with a subdomain (e.g. `dev.mydomain.com`). 

In the hosted zone in your prod account, you must then define an NS record with the values for your `dev` subdomain, such as:

![image](https://user-images.githubusercontent.com/1448524/167018213-adc448b6-1915-4e73-bb8f-237fc8b9ceb8.png)

Here a step by step guide: [Share Route 53 Domains Across AWS Accounts](https://serverless-stack.com/chapters/share-route-53-domains-across-aws-accounts.html)

Hope this helps!

**Comment by trevorallred** [comment]
OK, so `backend/goldstack.json` looks something like this?

```json
{
  "$schema": "./schemas/package.schema.json",
  "name": "backend",
  "template": "serverless-api",
  "templateVersion": "0.1.14",
  "deployments": [
    {
      "name": "dev",
      "configuration": {
        "hostedZoneDomain": "dev.example.com",
        "cors": "www.dev.example.com",
        "apiDomain": "api.dev.example.com",
      },
      "awsUser": "dev-user",
    },
    {
      "name": "prod",
      "configuration": {
        "hostedZoneDomain": "example.com",
        "cors": "www.example.com",
        "apiDomain": "api.example.com",
      },
      "awsUser": "prod-user",
    }
  ]
}
```

And `frontend/goldstack.json` looks something like this?

```json
{
  "$schema": "./schemas/package.schema.json",
  "name": "frontend",
  "template": "app-nextjs",
  "templateVersion": "0.1.14",
  "deployments": [
    {
      "name": "dev",
      "configuration": {
        "defaultCacheDuration": 10,
        "hostedZoneDomain": "dev.example.com",
        "websiteDomain": "www.dev.example.com",
        "websiteDomainRedirect": "dev.example.com"
      },
      "awsUser": "dev-user",
    },
    {
      "name": "prod",
      "configuration": {
        "defaultCacheDuration": 10,
        "hostedZoneDomain": "example.com",
        "websiteDomain": "www.example.com",
        "websiteDomainRedirect": "example.com"
      },
      "awsUser": "prod-user",
    }
  ]
}
```

**Comment by mxro** [comment]
Yes that looks right!

And then a hosted zone for `dev.example.com` would have to be configured in the AWS account accessible by `dev-user` and a hosted zone `example.com` configured in the AWS account accessible by `prod-user` (+ a NS record added to `example.com` that points to the nameservers (NS) for `dev.example.com`)

**Comment by trevorallred** [comment]
Thanks! This has worked for me.
