### ISSUE TITLE
Incorrect check for structured HTTP response

### ISSUE THREAD

**Issue by RobertGardner** [goldstack/goldstack#175]
At [this location](https://github.com/goldstack/goldstack/blob/e3c9fdc06e5c46cb24dd8dc401ba4fdb7903caf0/workspaces/templates-lib/packages/utils-aws-http-api-local/src/expressRequestToHttpApiGatewayEvent.ts#L189) in the code it checks to see if a structured response is being returned from a Lambda handler.

This is done with the code `if (result.body)`. There are two problems with this:
* First, this is false if `body` contains an empty string, which is a legitimate response
* Second, the [AWS spec](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.response) says that AWS looks at `result.statusCode`, not at `result.body`. So you cannot return, say, a 404 response by simply returning `{ statusCode: 404 }`. Instead, you have to return something like `{ statusCode: 404, body: JSON.stringify('Not found') }`. In addition to being awkward, this puts a body into the response that may not be wanted.

**Comment by mxro** [comment]
Thanks for raising this issue! That is a good point!

Does this PR look like it could resolve the issue? https://github.com/goldstack/goldstack/pull/176

**Comment by RobertGardner** [comment]
That was quick! Thanks. It looks correct to me.

**Comment by mxro** [comment]
PR merged and fix released. Should be enough to update the following dev dependency to `0.1.27` in any existing projects:

```
"@goldstack/utils-aws-http-api-local": "0.1.27",
```

For new projects, updated template should be released into production in the next 30 min or so.

Hope this resolves the issue!
