### ISSUE TITLE
No event body in serverless-api when running locally

### ISSUE THREAD

**Issue by RobertGardner** [goldstack/goldstack#178]
I'm using the serverless-api template and running it locally. When I use Postman to send requests to my app, the body does not appear anywhere in the request event.

Looking at the code, it appears the body should have been assigned [here](https://github.com/goldstack/goldstack/blob/e3c9fdc06e5c46cb24dd8dc401ba4fdb7903caf0/workspaces/templates-lib/packages/utils-aws-http-api-local/src/expressRequestToHttpApiGatewayEvent.ts#L96). As it stands, there seems to be no way for the body to get set in the event.

**Comment by RobertGardner** [comment]
This [PR](https://github.com/goldstack/goldstack/pull/180) should fix this issue.

**Comment by mxro** [comment]
PR merged and fix deployed with version [`@goldstack/utils-aws-http-api-local (0.1.28)`](https://www.npmjs.com/package/@goldstack/utils-aws-http-api-local).

Patched [Serveless API](https://goldstack.party/templates/lambda-api) template should also be deployed in the next few hours.
