### ISSUE TITLE
No headers in serverless-api response when running locally

### ISSUE THREAD

**Issue by RobertGardner** [goldstack/goldstack#179]
I'm using the serverless-api template and running it locally. When I use Postman to send requests to my app, the response does include any of my headers (except Content-Type).

Looking at the code, it appears the headers should have been assigned [here](https://github.com/goldstack/goldstack/blob/fbafa6b339c34c1ef2af7c8b81bc49aa8e9c2c1c/workspaces/templates-lib/packages/utils-aws-http-api-local/src/expressRequestToHttpApiGatewayEvent.ts#L192).

**Comment by RobertGardner** [comment]
This [PR](https://github.com/goldstack/goldstack/pull/180) should fix this issue.

**Comment by mxro** [comment]
PR merged and fix deployed with version [`@goldstack/utils-aws-http-api-local (0.1.28)`](https://www.npmjs.com/package/@goldstack/utils-aws-http-api-local).

Patched [Serveless API](https://goldstack.party/templates/lambda-api) template should also be deployed in the next few hours.
