### ISSUE TITLE
[utils-typescript-references] Option to ignore some packages

### ISSUE THREAD

**Issue by dobesv** [goldstack/goldstack#210]
A command-line option to exclude specific dependencies would be a nice to have.

We have some packages that provide tools and are not actually imported by the code in the package that dependends on them.  It would be nice not to insert a typescript reference for those tools.  This command line option would allow that.

**Comment by mxro** [comment]
Thanks for raising the issue! That sounds like a good idea. A new version has been released [`@goldstack/utils-typescript-references@0.2.2`](https://www.npmjs.com/package/@goldstack/utils-typescript-references).

I've added two new options `--excludeInReferences` and `--excludeInRoot`. Could you check the [documentation](https://github.com/goldstack/goldstack/tree/master/workspaces/templates-lib/packages/utils-typescript-references#--excludeinreferences) and see if that is what you were looking for?

**Comment by dobesv** [comment]
Thanks, looks good to me.
