### ISSUE TITLE
VSCode error related to line endings

### ISSUE THREAD

**Issue by Shalveena** [goldstack/goldstack#217]
When I installed the project and opened the project files, a lot of the files showed errors (particularly for the line endings):

```
Delete `␍`eslint[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)
Expected linebreaks to be 'LF' but found 'CRLF'.eslint[linebreak-style](https://eslint.org/docs/rules/linebreak-style)
```

My VSCode seems to be configured for 'CRLF' line endings; don't know if maybe this is related to the error?
![image](https://user-images.githubusercontent.com/69717354/173207054-66a6989b-7e6e-49eb-8679-6782bc8d05f7.png)

**Comment by Shalveena** [comment]
Update: resolved on my local copy by changing line endings to LF in VSCode and updating `autocrlf` setting to 'input' in my gitconfig file.

It might be useful to add the following workspace setting to the template: Found this link showing a possible solution: creating a gitattributes file. 
https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/#a-simple-gitattributes-config

**Comment by mxro** [comment]
New release [v0.4.4](https://github.com/goldstack/goldstack/releases/tag/v0.4.4) should include additional `.gitattributes` configuration.

**Comment by mxro** [comment]
This seems to be resolved now.
