### ISSUE TITLE
Unable to link to external goldstack repository

### ISSUE THREAD

**Issue by sivarcot** [goldstack/goldstack#286]
I would like to contribute to goldstack and test my changes along side another project. I followed instructions from https://github.com/goldstack/goldstack/blob/ab8fd2102f092871e03e8d232363d4a48b92efb3/CONTRIBUTING.md and from the other project I get the following. Am I missing something? Thanks!

> $ cd <OTHER PROJECT>
> $ yarn link ../goldstack -Apr
> $ yarn build
> node:internal/modules/cjs/loader:998
>   throw err;
>   ^
> 
> Error: Cannot find module 'source-map-support'
> Require stack:
> - /home/phil/projects/goldstack/workspaces/templates-lib/packages/template-nextjs/bin/template
>     at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
>     at Module._load (node:internal/modules/cjs/loader:841:27)
>     at Module.require (node:internal/modules/cjs/loader:1061:19)
>     at require (node:internal/modules/cjs/helpers:103:18)
>     at Object.<anonymous> (/home/phil/projects/goldstack/workspaces/templates-lib/packages/template-nextjs/bin/template:4:1)
>     at Module._compile (node:internal/modules/cjs/loader:1159:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
>     at Module.load (node:internal/modules/cjs/loader:1037:32)
>     at Module._load (node:internal/modules/cjs/loader:878:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/phil/projects/goldstack/workspaces/templates-lib/packages/template-nextjs/bin/template'
>   ]
> }
> 
> Node.js v18.12.1
>

**Comment by mxro** [comment]
Thank you for raising this issue and sorry for my delayed reply.

Did you run the command `yarn link ../goldstack -Apr` in the root of the project (so not in `templates/nextjs`)?

Did you run `yarn` in the goldstack repo after cloning it?

When I run

```
yarn
yarn link ../goldstack/ -Apr
yarn build
```

In a newly downloaded project, I get a different error message:

```
Max@DESKTOP-B5B5HEH MINGW64 ~/repos/genproject
$ yarn build
➤ YN0000: Done in 0s 498ms
Updating project references in tsconfig.json to:
  packages/app-nextjs
../goldstack/workspaces/utils/packages/esbuild-ssr-css-modules-plugin/src/esbuildSsrCssModulesPlugin.ts:1:63 - error TS2307: Cannot find module 'esbuild' or its corresponding type declarations.

1 import { OnLoadArgs, OnLoadResult, Plugin, PluginBuild } from 'esbuild';
                                                                ~~~~~~~~~
Found 1 error.
```

Not sure where this is coming from - will investigate this as well - but don't want to go down too far that problem if you are encountering a different one.

---

Possible workaround for now could be to copy your project into the cloned goldstack repo: https://github.com/goldstack/goldstack/blob/ab8fd2102f092871e03e8d232363d4a48b92efb3/CONTRIBUTING.md#copy-your-generated-project-as-a-yarn-workspace-under-a-local-goldstack-monorepo

**Comment by mxro** [comment]
I figured out the solution to the error I encountered (Cannot find module 'esbuild')

It is to move `esbuild` from a devDependency to a normal depenedency in this file:

https://github.com/goldstack/goldstack/blob/master/workspaces/utils/packages/esbuild-ssr-css-modules-plugin/package.json#L47

After that, building the Next.js project runs without errors for me.

However, I am a bit hesitant to commit that change to master, since `esbuild` `should` be a dev dependency, since we only use it's types here, and I am not sure why this doesn't work with linking the project!

**Comment by sivarcot** [comment]
Resolving the issue as my problem came from incompatible dependencies in my project. I had to pull the same dependencies as in the latest provided goldstack templates + rm -rf nodes_modules && yarn.

Thanks for your prompt replies!

**Comment by sivarcot** [comment]
Actually I am reopening as I found other weird behaviors. All pulling from scratch it fails elsewhere:
```
$ git clone  https://github.com/goldstack/goldstack.git
$ cd goldstack
$ yarn
$ yarn compile
$ yarn build
```

Switching to the generated goldstack project from the website

```
$ cd ..
$ mkdir test
$ cd test
$ unzip ~/Downloads/package.zip
$ yarn
$ yarn deploy
➤ YN0000: template set-nextjs-env <deployment>
➤ YN0000: 
➤ YN0000: Set NextJs environment variables
➤ YN0000: 
➤ YN0000: Positionals:
➤ YN0000:   deployment  Name of the deployment this command should be applied to
➤ YN0000:                                                              [string] [required]
➤ YN0000: 
➤ YN0000: Options:
➤ YN0000:   --version  Show version number                                       [boolean]
➤ YN0000:   --help     Show help                                                 [boolean]
➤ YN0000: 
➤ YN0000: Not enough non-option arguments: got 0, need at least 1
➤ YN0000: Done in 1s 141ms
```


calling template works by default

Now linking with the local goldstack source

```
$  yarn link ../goldstack -Apr
$ yarn deploy
YN0000: /home/phil/projects/goldstack/workspaces/utils/packages/utils-cli/src/utilsCli.ts:1
➤ YN0000: type AsyncFunction<O> = () => Promise<O>;
➤ YN0000:      ^^^^^^^^^^^^^
➤ YN0000: 
➤ YN0000: SyntaxError: Unexpected identifier
➤ YN0000:     at Object.compileFunction (node:vm:360:18)
➤ YN0000:     at wrapSafe (node:internal/modules/cjs/loader:1088:15)
➤ YN0000:     at Module._compile (node:internal/modules/cjs/loader:1123:27)
➤ YN0000:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
➤ YN0000:     at Object.require$$0.Module._extensions..js (/home/phil/projects/test/.pnp.cjs:24689:33)
➤ YN0000:     at Module.load (node:internal/modules/cjs/loader:1037:32)
➤ YN0000:     at Function.require$$0.Module._load (/home/phil/projects/test/.pnp.cjs:24526:14)
➤ YN0000:     at Module.require (node:internal/modules/cjs/loader:1061:19)
➤ YN0000:     at require (node:internal/modules/cjs/helpers:103:18)
➤ YN0000:     at Object.<anonymous> (/home/phil/projects/goldstack/workspaces/templates-lib/packages/template-nextjs/src/templateNextjs.ts:1:1)
➤ YN0000: Done in 0s 279ms
```

**Comment by sivarcot** [comment]
ok so above error is because we are running the JS runtime instead of the typescript one. So instead of calling "yarn deploy", we should be calling "yarn deploy-ts". Hence resolving

**Comment by mxro** [comment]
Great that all could be sorted out! If you have any further questions, don't hesitate to reach out!

Planning on standardising all deploy commands to the way `deploy-ts` works. That should resolve this potential problem then!
