### ISSUE TITLE
yarn build: Unknown Syntax Error: Command not found; did you mean:

### ISSUE THREAD

**Issue by adderpositive** [goldstack/goldstack#65]
node version -  v16.13.2
yarn version - 3.1.1
docker version - 20.10.12

Error:
`% yarn  build`

> Unknown Syntax Error: Command not found; did you mean:
> 
> $ yarn workspaces list [--since] [-R,--recursive] [-v,--verbose] [--json]
> While running workspaces foreach run clean

but i do not have any clue, where can be problem.

**Comment by mxro** [comment]
Thank you for raising this issue!

What operating system are you using?

It looks like there may be a problem with the yarn workspaces plugin that will enable the [`foreach` operation](https://yarnpkg.com/cli/workspaces/foreach). Does your plugins folder look as follows:

![image](https://user-images.githubusercontent.com/1448524/150216308-e80ba4c9-aa41-4a41-b782-de7f2e8c4b48.png)

Could you try running `yarn plugin import @berry/plugin-workspace-tools` as suggested in https://github.com/yarnpkg/berry/issues/364?

The plugins should have been loaded automatically with the template - strange that didn't happen!

**Comment by adderpositive** [comment]
Thank you. It works. Sorry, I am using yarn first time. :) Btw. love your project!

**Comment by mxro** [comment]
Glad to hear it worked! If you have any other questions, be welcome to raise another issue!
