### ISSUE TITLE
Provide more clarity on what email is used for

### ISSUE THREAD

**Issue by Shalveena** [goldstack/goldstack#74]
The download page no longer requires the user's email? Previously, when it was there, it didn't provide any info to users as to why they should provide their email address - what benefits it gives.

**Comment by mxro** [comment]
Suggested design:

![image](https://user-images.githubusercontent.com/1448524/151240005-a0bad7e5-c50d-4911-bef1-cb203207de8b.png)

**Comment by mxro** [comment]
Please see PR above for details on what was changed. Release to production with https://github.com/goldstack/goldstack/releases/tag/v0.3.11
