### ISSUE TITLE
Improve download page to guide users what to do next

### ISSUE THREAD

**Issue by Shalveena** [goldstack/goldstack#75]
At the moment, the download page ("Ready to download") doesn't give much guidance to users as to what to do after they download the package. 

It would be great if the page could have some next steps that the users can do.

**Comment by mxro** [comment]
Suggested new flow:

![image](https://user-images.githubusercontent.com/1448524/151239249-a780e61c-2f77-40af-8e4c-7f6a06f9f41a.png)

![image](https://user-images.githubusercontent.com/1448524/151239302-3b3c7f5b-02af-45de-b0a4-e545d3b40fff.png)

![image](https://user-images.githubusercontent.com/1448524/151239339-b14faec1-ffc8-4105-8cb6-220efebac744.png)

![image](https://user-images.githubusercontent.com/1448524/151239383-0ef76a72-d533-4b78-b9d4-0fb3824a3d59.png)

**Comment by mxro** [comment]
Release to production with https://github.com/goldstack/goldstack/releases/tag/v0.3.10 - does this look better?

**Comment by Shalveena** [comment]
Great work! The new download page is AMAZING! Much easier to follow and get started quickly. The step by step directions were a great idea. 

Quick note: Might be good to just add in a step, between the current steps 4 and 5, about how to install yarn.

**Comment by mxro** [comment]
Added an additional step now and deployed with https://github.com/goldstack/goldstack/releases/tag/v0.3.11 - does that look alright?
