### ISSUE TITLE
Improve Getting Started Documentation for Templates

### ISSUE THREAD

**Issue by Shalveena** [goldstack/goldstack#77]
The download page has a bit at the bottom about "Getting Started", under which there are links to the project setup and other info. At the moment, these are the only guidance that users are receiving as to what to do after downloading the package, so I imagine they would often click on these links. However, the content in these docs can be overwhelming - lots of words, small text, hard to read etc. It would be better to have some short, clear instructions that are easy to follow/read.

**Comment by mxro** [comment]
Also see #75

**Comment by mxro** [comment]
Getting started documentation has been updated in the [documentation](https://github.com/goldstack/goldstack/issues/110) ([Goldstack Getting Started](https://docs.dev.goldstack.party/docs/goldstack/getting-started)) and on the [download page](https://github.com/goldstack/goldstack/issues/75).

Does this look better now?

**Comment by mxro** [comment]
Closing this issue for now - if there are any further changes to the documentation required, please be welcome to raise another issue.
