### ISSUE TITLE
Make it possible/easy to contribute to the repository

### ISSUE THREAD

**Issue by mxro** [goldstack/goldstack#94]
Currently it is quite difficult to contribute code to the Goldstack repository due to lack of documentation and some potential incompatbilities in the GitHub actions build.

- [ ] Add a Contribute section to the project Readme or the [Goldstack Documentation](https://docs.goldstack.party/docs)
- [ ] Ensure GitHub actions build will work without problems in Forked projects

See #17

**Comment by chrismilleruk** [comment]
Thanks for adding this info, it might be worth considering a [CONTRIBUTING.md file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors#examples-of-contribution-guidelines), leaving README.md for your end users.

Dropping a list of hopefully daft questions here (I'm sure I could figure some of these out but you probably have a good workflow already)..

- I *think* that if I wanted to work on anything `yarn infra *`: The entry point is [utils-terraform/src/utilsTerraform.ts](https://github.com/goldstack/goldstack/blob/master/workspaces/templates-lib/packages/utils-terraform/src/utilsTerraform.ts). With AWS Auth handled in [infra-aws/src/infraAws.ts](https://github.com/goldstack/goldstack/blob/master/workspaces/templates-lib/packages/infra-aws/src/infraAws.ts). The `infra *` -> `terraform *` mapping / business logic in [utils-terraform/src/terraformBuild.ts](https://github.com/goldstack/goldstack/blob/master/workspaces/templates-lib/packages/utils-terraform/src/terraformBuild.ts) and the docker execution itself in [utils-terraform/src/terraformCli.ts](https://github.com/goldstack/goldstack/blob/master/workspaces/templates-lib/packages/utils-terraform/src/terraformCli.ts)
  - Is this right?

- To use these changes in a `generated project` then I would need to download `goldstack/goldstack`, make changes, build & confirm successful, then switch to the generated project and point some* of the dependencies to `goldstack` using `yarn add file://` or `yarn add link://` or `yarn link` or add to `package.json - "workspaces": []`?

- I guess I probably only need to point `template -> /template-lib/` but this might be incorrect?

- Once the `generated project` is referencing local modules in `goldstack/goldstack`, what's the dev workflow? is editing source in local modules enough to affect the generated project? or do I need to run a build command(s) after every change?

- Any coding standards etc.? Are they mostly covered by eslint, prettier, etc.? 

- After I'm done. How do I detach/restore the `generated project` from local modules to public modules (e.g. `yarn unlink`? etc.)

**Comment by mxro** [comment]
Thanks for the comments and questions!!

I have moved the contributing guidelines into a seperate file, thank you, see #97.

> I think that if I wanted to work on anything yarn infra *: The entry point is [utils-terraform/src/utilsTerraform.ts](https://github.com/goldstack/goldstack/blob/master/workspaces/templates-lib/packages/utils-terraform/src/utilsTerraform.ts). With AWS Auth handled in [infra-aws/src/infraAws.ts](https://github.com/goldstack/goldstack/blob/master/workspaces/templates-lib/packages/infra-aws/src/infraAws.ts). The infra * -> terraform * mapping / business logic in [utils-terraform/src/terraformBuild.ts](https://github.com/goldstack/goldstack/blob/master/workspaces/templates-lib/packages/utils-terraform/src/terraformBuild.ts) and the docker execution itself in [utils-terraform/src/terraformCli.ts](https://github.com/goldstack/goldstack/blob/master/workspaces/templates-lib/packages/utils-terraform/src/terraformCli.ts)

I'll see if I can add some documentation for this later but will first try to answer this here! There are a couple of steps to go through, since the logic is divided up into lots of small modules.

Essentially if we have a template, such as the Serverless API template https://github.com/goldstack/goldstack/blob/master/workspaces/templates/packages/serverless-api/package.json#L19 that runs as a Node.js executable, which will call a module when there is an infra operation https://github.com/goldstack/goldstack/blob/master/workspaces/templates-lib/packages/template-lambda-api/src/templateLambdaApi.ts#L67

This will then take us to https://github.com/goldstack/goldstack/blob/master/workspaces/templates-lib/packages/utils-terraform-aws/src/utilsTerraformAws.ts#L101 which connects up infraAws and utilsTerraform and the remainder is as you describe!

Lots of small modules floating around here, but the idea here was to have a lot of different building blocks that templates can be composed from. In any case, always happy for ideas to make things clearer and simpler since a lot of this has also grown organicially.

> To use these changes in a generated project then I would need to download goldstack/goldstack, make changes, build & confirm successful, then switch to the generated project and point some* of the dependencies to goldstack using yarn add file:// or yarn add link:// or yarn link or add to package.json - "workspaces": []?

I think there are two main ways here. To make small patches, I think using the Yarn https://yarnpkg.com/cli/patch command could work, e.g. `yarn patch @goldstack/infra-aws` and that can then be edited directly in the downloaded template. However, I haven't used the patch command myself and can also imagine that things would become quite unwieldy quickly.

The other way would be to clone the whole Goldstack repo and either edit or make a copy of any of the templates defined here: https://github.com/goldstack/goldstack/tree/master/workspaces/templates (or copy into there a package from a generated project, that should work as well) These are all wired up to use the latest versions of the libraries. Only thing to keep in mind is that we need to run any scripts with `ts-node` since running nodejs 'binary' scripts is otherwise not so easy to do when using TypeScript. See a script here: https://github.com/goldstack/goldstack/blob/master/workspaces/templates/packages/serverless-api/package.json#L20

So this enables then to test the changed libraries right there and then locally by running `yarn template-ts infra ...`

Then once everything works, can raise a PR against this repo, and when we merge it in, it will npm publish the new library versions that can then be used in any template (by bumping the version in the dependencies in the packages in the generated project). Unfortunately I think there will probably be errors in the GH actions in a forked repo, so if you want to branch off within this repo, just let me know and I can add you as collaborator.

Please let me know if you run into any problems, happy to help!

> Any coding standards etc.? Are they mostly covered by eslint, prettier, etc.?

Should all be configured in eslint and prettier!

**Comment by chrismilleruk** [comment]
I tried a few things to get this up and running nicely but I think changes to the way the build process handles the `package.json` would be required. I haven't tested the `yarn template-ts infra .` approach yet, but thought I'd check in.

Commands performed from the generated repo: 

`yarn patch @goldstack/*` creates a new temp folder and unpacks the contents on `npm` there. The structure is as follows:
```
<root>/dist/src/*
<root>/package.json ('main': 'dist/src/X.ts')
```
No obvious way to edit the source files and have the build files land in this folder without much trickery.

`yarn link --all /path/to/goldstack/goldstack`
Runs through ALL packages in goldstack/goldstack and replaces `goldstack/*` dependencies in the generated repo with a [resolution](https://yarnpkg.com/configuration/manifest#resolutions) to the folder in goldstack/goldstack containing `package.json`. The structure is as follows:
```
<root>/dist/src/*
<root>/src/*
<root>/package.json ('main': 'src/X.ts')
```
This errors as it stands, but if I update package.json with the `publishConfig` (i.e. `'main': 'dist/src/X.ts') then it doesn't error any more.

NB. I timed out for today and didn't get as far as affecting the functionality of `yarn infra` in the generated repo (ie. adding warnings, re-running builds etc) but it seems promising.

The question then would be how to temporarily update all `package.json` files in-place with the `publishConfig`, and is it a bad idea..

**Comment by mxro** [comment]
Ah yes, I guess since the packages published to npm will only have the generated code, the `patch` approach will probably not work. I should have thought about this before!

Okay, so they other approach is to link a locally cloned `goldstack/goldstack` repo with the generated project. That's a good idea as well but I haven't tested this before. But I think it offers a very interesting way to contribute to the repo, since then it can be developed alongside the generated project.

I guess another option would also be to clone the whole Goldstack repo and add a new workspace that contains the project? Then the yarn workspace resolution would take care of all the linking?

**Comment by chrismilleruk** [comment]
Good idea on the nesting. The error when accessing the source was something to do with typescript not wanting to share types externally. 

It would be a lot nicer if yarn workspace could handle it.

**Comment by mxro** [comment]
I have tested embedding a generated workspace in the monorepo project and at least the `yarn install` seems to work without problems:

https://github.com/goldstack/goldstack/pull/103

If you think the above could be useful, be welcome to merge the PR, so the gitignore file will be updated!

**Comment by chrismilleruk** [comment]
As an aside on this, I got debugging working with the following `launch.json` config.

I guess the best place for this is the docs?

.vscode/launch.json
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "app-nextjs > yarn template",
            "command": "yarn template-ts infra terraform dev version",
            "request": "launch",
            "type": "node-terminal",
            "cwd": "${workspaceRoot}/packages/app-nextjs/",
        }
    ]
}
```

**Comment by mxro** [comment]
I am not familiar with debugging in VSCode. So this will configure a launch program button?

![image](https://user-images.githubusercontent.com/1448524/156646565-fe2d084a-23e3-4385-ba93-98183d312bc7.png)

Assuming this would need to be a project-wide config? (So we couldn't generate it in the folders for the individual templates) - since I think this could be useful for launching the main `watch` scripts?

This particular one would be for running the Terraform, so I guess that could go into the `CONTRIBUTE.template.md`?

**Comment by mxro** [comment]
Contributing guidelines have been added and [workflows improved](https://github.com/goldstack/goldstack/issues/138). Closing this issue for now; for any additional improvements, we can reopen this issue or create a new one!
